id: I6D865851
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T22:07:35+00:00'
last_modified: '2022-06-08T08:01:50.610951+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01614
  title: ཤངས་ལུགས་མཁའ་སྤྱོད་དཀར་དམར་གཉིས་ཀྱི་ཚོགས་མཆོད་དང་རྗེས་ཆོག་ཕྲིན་ལས་ཡར་འཕེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    991A:
      image_group_id: I00KG02866
      title: ''
      total_pages: 12
      order: 1
      base_file: 991A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
